### PR TITLE
Ensure author ID has a value.

### PR DESCRIPTION
**Pull request by onegreypaw**
If the cron task is running at that point, then the $author_id value will be 0, but it should be $post->post_author as previously set above.

### CODE REVIEW

**Comment by jamiechong** [comment]
Hey Thanks for the PRs. I'll review in the next day or two and get them posted to wp.org. You've been using these changes in your own production env without issue?

**Comment by onegreypaw** [comment]
Heyo, full disclosure here, I work for Disney and we're using your plugin on one of our sites, probably about 1 month into using it and it's been great. The 2 PRs this week have been my responses to bugs that our internal QA team has written up. We have not yet pushed these 2 changes to production but have them on our QA and Stage (pre-production) environments. 

The only other mod we've done to the plugin is to comment out the "if (!is_cron())..." check in your init() function. We do this since we want the cron to its thing, but also want it to save a normal WP revision (and our pages are heavily dependant on ACF). Without commenting these lines out, cron scheduled revisionize variants wouldn't create a normal WP revision when it did its revisionize thing.
e.g.,
...
    // if (!is_cron()) {
      add_action('acf/save_post', __NAMESPACE__.'\\acf_on_publish_post', 130, 1);
    // }
...
 
We will be going to production with our latest updates in ~2 weeks. If you want me to ping you back after that I certainly can do.

**Comment by onegreypaw** [comment]
I should also mention with the change to comment out "if (!is_cron())...", we have also implemented actions for your "revisionize_before_publish" and "revisionize_after_publish" hooks in a small class so we can take advantage of static properties. 

The issue was this: after the cron task had run to schedule a revisionize variant and the normal WP revision was created, the author ID of the normal WP revision was set to 0, so the revisions line in admin UI of a post would look like: 
```, 21 hours ago (June 20, 2018 @ 14:40:06)```
Instead of:
```admin, 18 hours ago (June 20, 2018 @ 17:05:08)```

To solve this, in the "revisionize_before_publish" action, we save the author ID of the revisionize variant in a static property, then in the "revisionize_after_publish" action we load up the latest WP revision and if the author is 0 and set it back to the author of the revisionize variant. 

I can probably share that code with you, if interested.

**Comment by jamiechong** [comment]
It's great to have some corporate QA teams identify these edge cases - it benefits the community for sure. So thanks!

I haven't done a ton of testing with scheduled posts (cron) and it's interesting to hear about the issues with the WP Revisions not being created when scheduled. We could work on a separate PR to fix that too. 

With wrt this PR, I'm uncertain how you're able to get into that `else` block with cron. Those author changes are only set when _creating a revision_ - when `$to == null`. With cron, only publishes should happen and this line should execute: `$author_id = $to->post_author;  // maintain original author.`. 

I'm probably overlooking something, so please correct me.

**Comment by onegreypaw** [comment]
Cool, you end up in the else block via cron when your settings say to make a backup of the currently live post. It's the backup of the live post that has its author missing.

**Comment by jamiechong** [comment]
Sweet I modified the code a bit - no point using `? :` and setting $author_id to itself ;) 

Will push these to wp.org soon. Thanks again!

**Pull request merged**
