### PR TITLE
Addon's can't load when custom addon's directory is specified

### PR DESCRIPTION
**Pull request by piscis**
When specifying a custom addon's path with the new addon's filter the filter overwriting the addon directory is not executed. 

At the moment it is possible to install a addon to the external directory but after the installation the plugin can't  be loaded because load_addons is exectued to early in the loop.

The PR moves the load_addons method to the init action to give other plugins and themes the chance to inject their filters and theirfor make it possible to load the addons.

### CODE REVIEW

**Comment by jamiechong** [comment]
Hmm weird. I had tested this and all worked well. From where are you adding the filter? A plug-in? Or theme functions.php?

**Comment by jamiechong** [comment]
I’m reluctant to move those calls to init. Would need to test a bunch for the timing of other actions and hooks.

**Comment by jamiechong** [comment]
Okay - I can reproduce this bug... sorry - somehow it broke, maybe as I was implementing the multisite compatibility. Will investigate further and get is sorted.

**Comment by piscis** [comment]
From the  parent theme functions PHP

**Pull request merged**
